HausDAO/daohaus-monorepo

- .github/workflows/ci_develop.yaml
- .github/workflows/ci_master.yaml
- None
Add ci for develop and master
None
- [ x App builds locally (run the build command for *any impacted package* and check for any errors before the PR)
> Add ci workflows

- apps/hub-app/src/components/Profile.tsx
- apps/hub-app/src/constants.ts
- libs/dao-data/src/Haus.ts
- libs/dao-data/src/Profile.ts
- None 
Fix process missing issues when importing haus
> Remove process from deps

- apps/hub-app/src/components/Profile.tsx
> Fix profile

- apps/hub-app/index.html
- apps/summon-app/index.html
- libs/daohaus-connect-feature/src/utils/defaults.ts
> Support wallet connect

- package.json
- yarn.lock
> Bump plugin version

- .github/workflows/ci_master.yaml
None
Fix broken skynet deploy
None
> fix master deploy

- apps/hub-app/jest.config.ts
- apps/jobs/dao-producer-job/.eslintrc.json
- apps/jobs/dao-producer-job/jest.config.ts
- apps/jobs/dao-producer-job/project.json
- apps/jobs/dao-producer-job/src/environments/environment.prod.ts
- apps/jobs/dao-producer-job/src/environments/environment.ts
- apps/jobs/dao-producer-job/src/main.ts
- apps/jobs/dao-producer-job/tsconfig.app.json
- apps/jobs/dao-producer-job/tsconfig.json
- apps/jobs/dao-producer-job/tsconfig.spec.json
- apps/summon-app/jest.config.ts
- jest.config.ts
- libs/abi-utilities/jest.config.ts
- libs/baal-contract-service/jest.config.ts
- libs/common-utilities/jest.config.ts
- libs/daohaus-connect-feature/jest.config.ts
- libs/ui/jest.config.ts
- migrations.json
None
Upgrade nx workspace and generate producer job
> Upgrade nx workspace to the latest

- .github/workflows/ci_develop.yaml
- apps/v3-subgraph/project.json
> Add alpha deploy

- libs/common-utilities/package.json
- libs/common-utilities/project.json
- libs/daohaus-connect-feature/project.json
- libs/tx-builder-feature/project.json
- libs/ui/project.json
- package.json
- yarn.lock
> Add pipelines

- .github/workflows/ci_develop.yaml
- apps/hub-app/project.json
- apps/summon-app/project.json
> Add in deploy staging command

- apps/hub-app/README.md
- apps/summon-app/README.md
- libs/ui/package.json
- Bumps ui version to 0.0.2
- Force build hub and summon
> Feature/UI release 0.0.2

- apps/hub-app/README.md
- apps/summon-app/README.md
- libs/dao-data/package.json
- libs/dao-data/src/types/query.types.ts
- libs/ui/package.json
- yarn.lock
> develop into master with updated ui release

- libs/common-utilities/package.json
- libs/dao-data/README.md
- libs/dao-data/package.json
- libs/daohaus-connect-feature/package.json
- libs/tx-builder-feature/package.json
- libs/ui/package.json
> Release/sdk release 0.0.3 (#338)

- apps/hub-app/src/components/BodyNav.tsx
- apps/hub-app/src/components/DaoCard.tsx
- apps/hub-app/src/components/FilterDropdown.tsx
- apps/hub-app/src/components/HomeDashboard.tsx
- apps/hub-app/src/components/Table.tsx
- apps/hub-app/src/components/TableControl.tsx
- apps/hub-app/src/pages/HomePage.tsx
- apps/hub-app/src/utils/constants.ts
- libs/common-utilities/src/utils/general.ts
- libs/dao-data/package.json
- libs/dao-data/project.json
- libs/dao-data/src/utils/transformers.ts
> develop into master 

- libs/daohaus-connect-feature/package.json
- libs/tx-builder-feature/package.json
- libs/ui/README.md
- libs/ui/package.json
> bump versions on feature packages

- libs/common-utilities/src/constants/endpoints.ts
N/A
was reviewing v3 and saw some networks missing; adding supported networks gnosis apis
https://docs.gnosis-safe.io/backend/available-services#safe-transaction-service
feel free to close if this this has unintended consequences
> reviewing v3 monorepo and saw some networks missing

- apps/hub-app/src/hooks/useDaoData.tsx
- libs/daohaus-connect-feature/project.json
- libs/daohaus-connect-feature/src/human-format.d.ts
- libs/daohaus-connect-feature/tsconfig.json
- libs/daohaus-connect-feature/tsconfig.lib.json
- libs/tx-builder-feature/src/utils/txBuilderUtils.ts
- libs/ui/project.json
- libs/ui/src/human-format.d.ts
- libs/ui/tsconfig.json
- libs/ui/tsconfig.lib.json
fixes https://github.com/HausDAO/daohaus-monorepo/issues/426 after new package deploys
N/A
> UI dao connect declarations

- libs/daohaus-connect-feature/package.json
- libs/ui/package.json
NA
need to bump versions so we get new packages on npm for UI and Connect Feature
> bumping versions for declaration publishing

- apps/summon-app/src/utils/content.ts
fixes https://github.com/HausDAO/daohaus-monorepo/issues/452
removing a period
> removing period from info content which casues confusing tooltip

- README.md
N/A
- updating readme with current apps and libs
- prefer table structure over heading and details
difference:
> Readme tables preferred

- apps/summon-app/src/layouts/SummonerForm.tsx
[Add a link to the GitHub issue.](https://github.com/HausDAO/daohaus-monorepo/issues/494)
Updated the heading to remove reference to Baal. Add link to Spencers article in the sub heading.
N/A
> Updated heading and subtext with link

- .github/ISSUE_TEMPLATE/test_report.yml
N/A
From testing work we wanted a template for reporting the results from testing
Can see it live here: https://github.com/plor/daohaus-app/issues/new?assignees=&labels=bug&template=test_report.yml
N/A
> Adds new issue template

- libs/dao-data/test/hubQuery.spec.ts
- libs/dao-data/test/queries.spec.ts
> fixes tests for new factory

- package.json
- yarn.lock
removing duplicate packages
removing duplicate packages from package.json; opting for higher version of `@storybook/core-server`
> chore: removing duplicate packages

- libs/common-utilities/package.json
- libs/dao-data/package.json
- libs/daohaus-connect-feature/package.json
- libs/form-builder/package.json
- libs/form-builder/project.json
- libs/form-builder/tsconfig.json
- libs/form-builder/tsconfig.lib.json
- libs/tx-builder-feature/package.json
- libs/tx-builder-feature/project.json
- libs/tx-builder-feature/tsconfig.json
- libs/tx-builder-feature/tsconfig.lib.json
- libs/ui/package.json
> bumping versions; fixing tx-builder and form-builder

- .github/dependabot.yml
- .vim/coc-settings.json
- .vscode/extensions.json
- .vscode/settings.json
fixes https://github.com/HausDAO/daohaus-monorepo/issues/455
extract default settings into monorepo so format on save is unified between vs code and vim with project wide settings
if anyone has anything to add here via vim config, would highly appreciate a review
a +1 is the monthly dependabot task, runs monthly
N/A
> Default editor settings

- nx.json
N/A
base branch for affected is defaulted to main, setting it to master as we have no main branch.
N/A
> updating main to master

- apps/summon-app/src/app/App.tsx
- apps/summon-app/src/layouts/ShamanSegment.tsx
- apps/summon-app/src/layouts/SummonError.tsx
- apps/summon-app/src/layouts/SummonerForm.tsx
- apps/summon-app/src/layouts/SummonerLoading.tsx
- apps/summon-app/src/layouts/SummonerSuccess.tsx
- libs/daohaus-connect-feature/src/components/ExplorerLink/ExplorerLink.tsx
[Add a link to the GitHub issue.](https://github.com/HausDAO/daohaus-monorepo/issues/608)
- add linkType external
- Update heading
- Update ExplorerLink component
- Requires a version bump
N/A
> Update links to add linkType external and ExplorerLink component

- apps/summon-app/src/layouts/SummonerForm.tsx
[Add a link to the GitHub issue.](https://github.com/HausDAO/daohaus-monorepo/issues/609)
- Removed period from heading on SummonerForm.tsx
- Loading Page heading was fixed here: https://github.com/HausDAO/daohaus-monorepo/pull/639
N/A
> Remove period from heading

- apps/summon-app/src/components/ConnectBox/ConnectBox.tsx
[Add a link to the GitHub issue.](https://github.com/HausDAO/daohaus-monorepo/issues/542)
- Changed: Connect wallet to a DAO
- To: Connect wallet to summon a DAO
N/A
> Add 'summon' to connect wallet copy

- libs/common-utilities/CHANGELOG.md
- libs/common-utilities/package.json
- libs/dao-data/CHANGELOG.md
- libs/dao-data/package.json
- libs/daohaus-connect-feature/CHANGELOG.md
- libs/daohaus-connect-feature/package.json
- libs/tx-builder-feature/CHANGELOG.md
- libs/tx-builder-feature/package.json
- libs/ui/CHANGELOG.md
- libs/ui/package.json
> Bump lib versions 2022 08 12 074241

- .github/workflows/ci_release.yml
- libs/common-utilities/CHANGELOG.md
- libs/common-utilities/package.json
- libs/common-utilities/project.json
- libs/dao-data/CHANGELOG.md
- libs/dao-data/package.json
- libs/dao-data/project.json
- libs/daohaus-connect-feature/CHANGELOG.md
- libs/daohaus-connect-feature/package.json
- libs/daohaus-connect-feature/project.json
- libs/tx-builder-feature/CHANGELOG.md
- libs/tx-builder-feature/package.json
- libs/tx-builder-feature/project.json
- libs/ui/CHANGELOG.md
- libs/ui/package.json
- libs/ui/project.json
> Bump lib versions 2022 08 16 092844

- libs/ui/src/components/molecules/FieldWrapper/FieldWrapper.stories.tsx
- libs/ui/src/components/molecules/FieldWrapper/FieldWrapper.styles.ts
- libs/ui/src/components/molecules/FieldWrapper/FieldWrapper.tsx
Related to #568 
Fix modifier button positioning within FieldWrapper to be fixed at the right
None
> Fix modifier button positioning on FieldWrapper

- apps/core-app/src/components/customFields/tributeInput.tsx
- apps/core-app/src/legos/contracts.ts
- apps/core-app/src/legos/form.ts
- apps/core-app/src/legos/tx.ts
- apps/core-app/src/pages/FormTest.tsx
- libs/tx-builder-feature/src/utils/args.ts
fixes #{https://github.com/HausDAO/daohaus-monorepo/issues/668}
Build form
NA
> Shares for token form

- libs/abi-utilities/CHANGELOG.md
- libs/abi-utilities/package.json
- libs/common-utilities/CHANGELOG.md
- libs/common-utilities/package.json
- libs/contract-utilities/CHANGELOG.md
- libs/contract-utilities/package.json
- libs/dao-data/CHANGELOG.md
- libs/dao-data/package.json
- libs/daohaus-connect-feature/CHANGELOG.md
- libs/daohaus-connect-feature/package.json
- libs/tx-builder-feature/CHANGELOG.md
- libs/tx-builder-feature/package.json
- libs/ui/CHANGELOG.md
- libs/ui/package.json
bumping lib versions
bump lib versions
> Bump lib versions 2022 08 30 050737

- apps/hub-app/src/components/DaoCard.tsx
- apps/hub-app/src/components/DaoTable.tsx
- libs/common-utilities/src/constants/chainData.ts
fixes https://github.com/HausDAO/daohaus-monorepo/issues/545
this was already fixed on the `DaoCard`, fixing it on the `DaoTable` and refactoring accessor
> Readable name dao table

- .github/ISSUE_TEMPLATE/provide_feedback.yml
- .github/ISSUE_TEMPLATE/report_bug.yml
- .github/ISSUE_TEMPLATE/request_feature.yml
https://github.com/HausDAO/daohaus-monorepo/issues/724
Add links to toolbox and make minor text updates
N/A
> Add links to toolbox and make minor text updates

- apps/core-app/src/legos/form.ts
#765 
Add proposal expiry "gated field" to all proposal forms
None
> Add expiry field to proposal forms

- apps/core-app/src/components/ProposalHistoryCard.tsx
- apps/core-app/src/components/VotingBar.tsx
- apps/core-app/src/components/proposalCards/ActionFailed.tsx
- apps/core-app/src/components/proposalCards/ActionPrimitives.tsx
- apps/core-app/src/components/proposalCards/BaseProposalCard.tsx
- apps/core-app/src/components/proposalCards/Cancelled.tsx
- apps/core-app/src/components/proposalCards/Expired.tsx
- apps/core-app/src/components/proposalCards/Failed.tsx
- apps/core-app/src/components/proposalCards/GracePeriod.tsx
- apps/core-app/src/components/proposalCards/HasNotVoted.tsx
- apps/core-app/src/components/proposalCards/HasVoted.tsx
- apps/core-app/src/components/proposalCards/Passed.tsx
- apps/core-app/src/components/proposalCards/ProposalActions.tsx
- apps/core-app/src/components/proposalCards/ReadyForProcessing.tsx
- apps/core-app/src/components/proposalCards/Unsponsored.tsx
- apps/core-app/src/legos/form.ts
- apps/core-app/src/pages/ProposalDetails.tsx
- apps/core-app/src/pages/Proposals.tsx
- libs/ui/src/components/atoms/Progress/Progress.styles.ts
- libs/ui/src/components/atoms/index.ts
fixes {https://github.com/HausDAO/daohaus-monorepo/issues/786}
fixes {https://github.com/HausDAO/daohaus-monorepo/issues/792}
Also fixes: 
- Adds in the new voting par and calcs percentages
- Rebuilds quorum component and spreads across cards
- Fixes some styles
^
> Proposal action/sweet treats

- apps/core-app/src/Routes.tsx
- apps/hub-app/src/Routes.tsx
- apps/summon-app/src/app/App.tsx
- libs/ui/src/components/molecules/Banner/Banner.styles.ts
- libs/ui/src/components/molecules/index.ts
Link to the [GitHub issue](https://github.com/HausDAO/daohaus-monorepo/issues/784).
Added Banner component to all apps to display that this is a Beta version. Fixed styles for mobile
NA
> Added Banner to two Apps, Fixed styles for mobile

- libs/ui/src/components/organisms/NavigationTabs/NavigationTabs.tsx
fixes https://github.com/HausDAO/daohaus-monorepo/issues/787
modal option fixes scroll --- maybe we should default it to?
> fix scrolling

- apps/summon-app/src/app/App.tsx
- apps/summon-app/src/layouts/SummonerSuccess.tsx
- libs/ui/src/components/atoms/Button/Button.tsx
fixes https://github.com/HausDAO/daohaus-monorepo/issues/798
> adding view dao link

- apps/core-app/src/components/GovernanceSettings.tsx
fixes https://github.com/HausDAO/daohaus-monorepo/issues/800
fixed
> fix gov settings

- libs/ui/src/components/molecules/Banner/Banner.tsx
https://github.com/HausDAO/daohaus-monorepo/issues/811
Change text in Beta Notice Component to "DAOhaus v3 is currently in beta. Please report bugs, request features or provide feedback."
N/A
> Update beta warning text

- apps/core-app/src/pages/Vaults.tsx
fixes https://github.com/HausDAO/daohaus-monorepo/issues/809 
forgot to push this up with last pr
> updating keys

- apps/core-app/src/components/proposalCards/ActionPrimitives.tsx
- apps/core-app/src/components/proposalCards/ProposalActions.tsx
- apps/core-app/src/pages/ProposalDetails.tsx
fixes https://github.com/HausDAO/daohaus-monorepo/issues/815
> fixing porposal percentage and card

- apps/core-app/src/components/Profile.tsx
- apps/core-app/src/components/customFields/ProposalOffering.tsx
- apps/core-app/src/legos/config.tsx
- apps/core-app/src/legos/fields.ts
- apps/core-app/src/legos/form.ts
- libs/common-utilities/src/constants/chainData.ts
- libs/dao-context/src/DaoContext.tsx
- libs/form-builder/src/components/FormBuilder.tsx
https://github.com/HausDAO/daohaus-monorepo/issues/684
See issue
> Proposal offering

- apps/core-app/src/components/customFields/ProposalOffering.tsx
#818 
Fix proposalOffering component to evaluate based on DAO sponsor threshold
None
> Fix proposalOffering to eval based on sponsorThreshold

- apps/core-app/src/components/customFields/SelectApplicant.tsx
- apps/core-app/src/utils/dataFetchHelpers.ts
None
On Ragequit, validate that the selected (or input) member owns dao shares
None
> ragequit: validate member owns shares

- apps/summon-safe-app/src/utils/summonTx.ts
- apps/summon-safe-app/src/views/Daos.tsx
#828 
Minor bug fixes were added after making sure the safe app is working with the newly deployed Baal contracts on GnosisChain
None
> SafeApp: minor bug fixes to be ready for production on GnosisChain

- libs/common-utilities/src/constants/endpoints.ts
None
Fix gas estimate endpoint for GnosisChain so it is possible to submit dao proposal Txs through the core-ui
None
> Fix gas estimate endpoint for GnosisChain

- .eslintignore
N/A
eslint is not for json, unless we add an eslint-json package
> ignoring json in eslint

- .github/workflows/ci_develop.yaml
- .github/workflows/ci_master.yaml
> properly named -- with VITE_

- apps/core-app/src/components/proposalCards/GracePeriod.tsx
> added closing paren

- apps/core-app/src/components/ActionDisplay.tsx
- apps/core-app/src/components/ButtonLink.tsx
- apps/core-app/src/components/MetadataSettings.tsx
- apps/core-app/src/components/NewProposalList.tsx
- apps/core-app/src/components/ProfileLink.tsx
- apps/core-app/src/components/ProposalDetailsGuts.tsx
- apps/core-app/src/pages/Dao.tsx
- apps/core-app/src/pages/DaoOverview.tsx
- apps/core-app/src/pages/Member.tsx
- apps/core-app/src/pages/Members.tsx
- apps/core-app/src/pages/Vaults.tsx
- libs/daohaus-connect-feature/src/components/ConnectButton/ConnectButton.tsx
- libs/daohaus-connect-feature/src/components/ConnectButton/ConnectButtonStyles.tsx
- libs/daohaus-connect-feature/src/components/ConnectButton/UserConnetedDropdown.tsx
- libs/daohaus-connect-feature/src/components/HausLayout/HausLayout.tsx
- libs/daohaus-connect-feature/src/components/NetworkButton/NetworkButton.tsx
- libs/ui/src/components/layouts/BiColumnLayout/BiColumn.styles.tsx
- libs/ui/src/components/layouts/OuterLayout/OuterLayout.tsx
- libs/ui/src/components/layouts/SingleColumnLayout/SingleColumnLayout.styles.tsx
- libs/ui/src/components/organisms/AppSwitcher/AppSwitcher.tsx
- libs/ui/src/components/organisms/Footer/Footer.tsx
- libs/ui/src/components/organisms/NavigationTabs/NavigationTabs.tsx
#848
#873
#871
#874
#875
#877
#885
#900
- A slew of mobile changes. 
- Some app structure changes to Core. 
- Some component changes.
- We need a DH connect V2 ticket, restructure proposal 
- Fixes some extra issues like margin above Proposal card helper text and removing the 'holder indicator' from 
> Mobilicious

- apps/core-app/src/components/ProposalHistoryCard.tsx
- apps/core-app/src/components/customFields/walletConnectLink.tsx
- apps/summon-app/src/layouts/AdvancedSegment.tsx
- apps/summon-app/src/layouts/SummonerSuccess.tsx
- libs/common-utilities/src/content/info.ts
Closes #851 #897 #894 
Multiple bug fixes in core and summoner apps
None
> Minor bug fixes

- apps/core-app/src/utils/historyHelpers.ts
Closes #914 
Fixes message on successfully completed proposal to include execution date only
None
> fix complete proposal msg

- libs/abi-utilities/CHANGELOG.md
- libs/abi-utilities/package.json
- libs/common-utilities/CHANGELOG.md
- libs/common-utilities/package.json
- libs/contract-utilities/CHANGELOG.md
- libs/dao-context/CHANGELOG.md
- libs/dao-data/CHANGELOG.md
- libs/dao-data/package.json
- libs/daohaus-connect-feature/CHANGELOG.md
- libs/daohaus-connect-feature/package.json
- libs/form-builder/CHANGELOG.md
- libs/form-builder/package.json
- libs/tx-builder-feature/CHANGELOG.md
- libs/tx-builder-feature/package.json
- libs/ui/CHANGELOG.md
- libs/ui/package.json
> Bump lib versions 2022 10 03 095623

- apps/core-app/src/pages/Dao.tsx
> fix proposal link

- apps/core-app/src/components/HomeDashboard.tsx
- apps/core-app/src/components/ProposalCardOverview.tsx
- apps/core-app/src/components/ProposalDetailsGuts.tsx
- apps/core-app/src/pages/Dao.tsx
- apps/hub-app/src/Routes.tsx
- apps/summon-app/src/app/App.tsx
- apps/summon-app/src/layouts/FormLayouts.tsx
- apps/summon-app/src/layouts/SummonError.tsx
- apps/summon-app/src/layouts/SummonerForm.tsx
- apps/summon-app/src/layouts/SummonerLoading.tsx
- apps/summon-app/src/layouts/SummonerSuccess.tsx
- libs/common-utilities/src/utils/units.ts
- libs/dao-data/src/subgraph/queries/proposals.generated.ts
- libs/dao-data/src/utils/proposalsStatus.ts
> Bug sweeper2

- apps/core-app/src/components/MetadataSettings.tsx
- apps/core-app/src/components/TagList.tsx
- apps/core-app/src/legos/form.ts
- apps/core-app/src/pages/ProposalDetails.tsx
- apps/core-app/src/pages/Safes.tsx
Corrections we made during Wednesday's testing session
See commits
> Corrections

- apps/core-app/src/components/proposalCards/Unsponsored.tsx
Closes #917 
Updates tooltip for sponsorship threshold
None
> fix sponsor tooltip

- libs/abi-utilities/CHANGELOG.md
- libs/abi-utilities/package.json
- libs/common-utilities/CHANGELOG.md
- libs/common-utilities/package.json
- libs/contract-utilities/CHANGELOG.md
- libs/contract-utilities/package.json
- libs/dao-context/CHANGELOG.md
- libs/dao-context/package.json
- libs/dao-data/CHANGELOG.md
- libs/dao-data/package.json
- libs/daohaus-connect-feature/CHANGELOG.md
- libs/daohaus-connect-feature/package.json
- libs/form-builder/CHANGELOG.md
- libs/form-builder/package.json
- libs/tx-builder-feature/CHANGELOG.md
- libs/tx-builder-feature/package.json
- libs/ui/CHANGELOG.md
- libs/ui/package.json
bumping lib versions
see commits
N/A
> Bump lib versions 2022 10 17 051754
